# Generated by Django 5.1.5 on 2025-03-04 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_users_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='profile_picture',
        ),
        migrations.AddField(
            model_name='users',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
