# Generated by Django 5.1.5 on 2025-03-04 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_users_profile_picture_users_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
